name: Github Linux Build

on:
  pull_request:
    branches: [ "**" ]

jobs:
  build-multiple-configurations:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure linux_threadx_debug
      working-directory: ${{github.workspace}}
      run: cmake --preset=linux_threadx_debug

    - name: Build linux_threadx_debug
      run: cmake --build --preset=linux_threadx_debug
  
    - name: Configure linux_freertos_debug
      working-directory: ${{github.workspace}}
      run: cmake --preset=linux_freertos_debug

    - name: Build linux_freertos_debug
      run: cmake --build --preset=linux_freertos_debug

    - name: Configure linux_test_debug
      working-directory: ${{github.workspace}}
      run: cmake --preset=linux_test_debug

    - name: Build linux_test_debug
      run: cmake --build --preset=linux_test_debug

    - name: Configure linux_debug
      working-directory: ${{github.workspace}}
      run: cmake --preset=linux_debug

    - name: Build linux_test
      run: cmake --build --preset=linux_debug
  
    - name: Configure linux_release
      working-directory: ${{github.workspace}}
      run: cmake --preset=linux_release

    - name: Build linux_release
      run: cmake --build --preset=linux_release