name: Github Linux unit test

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "main" ]

jobs:
  build-and-run-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: threeal/gcovr-action@v1.1.0

    - name: Configure linux_test_debug
      working-directory: ${{github.workspace}}
      run: cmake --preset=linux_test_debug

    - name: Build linux_test_debug
      run: cmake --build --preset=linux_test_debug

    - name: Running unit test
      working-directory: ${{github.workspace}}
      run: ctest preset=linux_test_debug --test-dir build_linux_test_debug/
    
    - name: Coverage
      working-directory: ${{github.workspace}}
      run: gcovr -r  . --filter=easy_embedded